// Copyright (c) 2026 Khulla Digital Library contributors.
// SPDX-License-Identifier: AGPL-3.0-only

// Checks that every handwritten Dart file carries the Khulla copyright
// header, so single-file copies keep our name on them (the root LICENSE
// alone does not travel with a copied file).
//
// The app is AGPL-3.0-only; the khulla_ui design system stays MIT so it can
// be reused on its own. See COMMERCIAL-LICENSE.md.
//
// Run `make copyright-check` in CI; run `make copyright` (`--fix` here) to
// stamp missing headers locally.
//
// Generated files are skipped: they are either gitignored (*.g.dart,
// *.freezed.dart, *.config.dart, lib/gen/, lib/l10n/gen/) or carry their
// own generator notice that must stay intact (drift schema snapshots and
// migration steps say GENERATED BY drift_dev, DO NOT MODIFY).
import 'dart:io';

const String _copyrightLine =
    '// Copyright (c) 2026 Khulla Digital Library contributors.';

/// Directories that carry a licence other than the app's.
const Map<String, String> _licenceOverrides = <String, String>{
  'packages/khulla_ui/': 'MIT',
};

const String _defaultLicence = 'AGPL-3.0-only';

/// The two lines [file] must start with.
List<String> _headerLinesFor(File file) {
  final path = file.path.replaceAll(r'\', '/');
  var licence = _defaultLicence;
  for (final entry in _licenceOverrides.entries) {
    if (path.startsWith(entry.key)) licence = entry.value;
  }
  return <String>[_copyrightLine, '// SPDX-License-Identifier: $licence'];
}

/// Handwritten sources live here. Platform shells (android/, ios/, linux/,
/// macos/, windows/) are Flutter scaffolding and stay untouched.
const List<String> _roots = <String>[
  'lib',
  'packages',
  'test',
  'script',
  'tools',
];

/// Generated file suffixes — matches the gitignored codegen outputs.
bool _isGeneratedName(String path) =>
    path.endsWith('.g.dart') ||
    path.endsWith('.freezed.dart') ||
    path.endsWith('.config.dart') ||
    path.endsWith('.mocks.dart');

/// Generated directories and build caches.
bool _isGeneratedDir(String path) =>
    path.contains('/gen/') ||
    path.contains('/generated/') ||
    path.contains('/.dart_tool/');

/// Skips files carrying their own generator notice (drift snapshots and
/// migration steps). Their notice must stay intact.
bool _hasGeneratorNotice(List<String> firstLines) =>
    firstLines.any((line) => line.contains('GENERATED BY'));

bool _hasHeader(String content, List<String> header) {
  final lines = content.split('\n');
  if (lines.length < header.length) return false;
  for (var i = 0; i < header.length; i++) {
    if (lines[i].trimRight() != header[i]) return false;
  }
  return true;
}

List<File> _handwrittenDartFiles(Directory root) {
  final files = <File>[];
  if (!root.existsSync()) return files;
  for (final entity in root.listSync(recursive: true, followLinks: false)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    if (_isGeneratedName(entity.path)) continue;
    if (_isGeneratedDir(entity.path)) continue;
    files.add(entity);
  }
  files.sort((a, b) => a.path.compareTo(b.path));
  return files;
}

void main(List<String> args) {
  final fix = args.contains('--fix');

  final candidates = <File>[];
  for (final name in _roots) {
    candidates.addAll(_handwrittenDartFiles(Directory(name)));
  }

  final offenders = <File>[];
  for (final file in candidates) {
    final content = file.readAsStringSync();
    final firstLines = content.split('\n').take(6).toList();
    if (_hasGeneratorNotice(firstLines)) continue;
    if (!_hasHeader(content, _headerLinesFor(file))) offenders.add(file);
  }

  if (fix) {
    for (final file in offenders) {
      final content = file.readAsStringSync();
      file.writeAsStringSync(
        '${_headerLinesFor(file).join('\n')}\n\n$content',
      );
    }
    stdout.writeln('Stamped ${offenders.length} file(s).');
    return;
  }

  if (offenders.isNotEmpty) {
    stderr.writeln(
      'Missing Khulla copyright header in ${offenders.length} file(s):',
    );
    for (final file in offenders) {
      stderr.writeln('  ${file.path}');
    }
    stderr.writeln('Run `make copyright` to add the missing headers.');
    exit(1);
  }
  stdout.writeln(
    'All ${candidates.length} handwritten file(s) carry the header.',
  );
}
